// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'study_year.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$StudyYearImpl _$$StudyYearImplFromJson(Map<String, dynamic> json) =>
    _$StudyYearImpl(
      id: json['id'] as int,
      numeroInscription: json['numeroInscription'] as String?,
      anneeAcademiqueId: json['anneeAcademiqueId'] as int?,
      anneeAcademiqueCode: json['anneeAcademiqueCode'] as String?,
      situationId: json['situationId'] as int?,
      dossierEtudiantId: json['dossierEtudiantId'] as int?,
      numeroMatricule: json['numeroMatricule'] as String?,
      ouvertureOffreFormationId: json['ouvertureOffreFormationId'] as int?,
      refCodeCycle: json['refCodeCycle'] as String?,
      refLibelleCycle: json['refLibelleCycle'] as String?,
      refLibelleCycleAr: json['refLibelleCycleAr'] as String?,
      ofIdDomaine: json['ofIdDomaine'] as int?,
      ofCodeDomaine: json['ofCodeDomaine'] as String?,
      ofLlDomaine: json['ofLlDomaine'] as String?,
      ofLlDomaineArabe: json['ofLlDomaineArabe'] as String?,
      ofIdFiliere: json['ofIdFiliere'] as int?,
      ofCodeFiliere: json['ofCodeFiliere'] as String?,
      ofLlFiliereArabe: json['ofLlFiliereArabe'] as String?,
      ofLlFiliere: json['ofLlFiliere'] as String?,
      ofIdSpecialite: json['ofIdSpecialite'] as int?,
      ofCodeSpecialite: json['ofCodeSpecialite'] as String?,
      ofLlSpecialiteArabe: json['ofLlSpecialiteArabe'] as String?,
      ofLlSpecialite: json['ofLlSpecialite'] as String?,
      individuId: json['individuId'] as int?,
      nin: json['nin'] as String?,
      individuNomArabe: json['individuNomArabe'] as String?,
      individuNomLatin: json['individuNomLatin'] as String?,
      individuPrenomArabe: json['individuPrenomArabe'] as String?,
      individuPrenomLatin: json['individuPrenomLatin'] as String?,
      individuDateNaissance: json['individuDateNaissance'] as String?,
      individuLieuNaissance: json['individuLieuNaissance'] as String?,
      individuLieuNaissanceArabe: json['individuLieuNaissanceArabe'] as String?,
      refEtablissementId: json['refEtablissementId'] as int?,
      refCodeEtablissement: json['refCodeEtablissement'] as String?,
      llEtablissementArabe: json['llEtablissementArabe'] as String?,
      llEtablissementLatin: json['llEtablissementLatin'] as String?,
      moyenneBac: (json['moyenneBac'] as num?)?.toDouble(),
      lastMoyenne: (json['lastMoyenne'] as num?)?.toDouble(),
      photo: json['photo'] as String?,
      cycleId: json['cycleId'] as int?,
      cycleCode: json['cycleCode'] as String?,
      cycleLibelleLongLt: json['cycleLibelleLongLt'] as String?,
      niveauId: json['niveauId'] as int?,
      niveauCode: json['niveauCode'] as String?,
      niveauRang: json['niveauRang'] as int?,
      niveauLibelleLongLt: json['niveauLibelleLongLt'] as String?,
      niveauLibelleLongAr: json['niveauLibelleLongAr'] as String?,
    );

Map<String, dynamic> _$$StudyYearImplToJson(_$StudyYearImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'numeroInscription': instance.numeroInscription,
      'anneeAcademiqueId': instance.anneeAcademiqueId,
      'anneeAcademiqueCode': instance.anneeAcademiqueCode,
      'situationId': instance.situationId,
      'dossierEtudiantId': instance.dossierEtudiantId,
      'numeroMatricule': instance.numeroMatricule,
      'ouvertureOffreFormationId': instance.ouvertureOffreFormationId,
      'refCodeCycle': instance.refCodeCycle,
      'refLibelleCycle': instance.refLibelleCycle,
      'refLibelleCycleAr': instance.refLibelleCycleAr,
      'ofIdDomaine': instance.ofIdDomaine,
      'ofCodeDomaine': instance.ofCodeDomaine,
      'ofLlDomaine': instance.ofLlDomaine,
      'ofLlDomaineArabe': instance.ofLlDomaineArabe,
      'ofIdFiliere': instance.ofIdFiliere,
      'ofCodeFiliere': instance.ofCodeFiliere,
      'ofLlFiliereArabe': instance.ofLlFiliereArabe,
      'ofLlFiliere': instance.ofLlFiliere,
      'ofIdSpecialite': instance.ofIdSpecialite,
      'ofCodeSpecialite': instance.ofCodeSpecialite,
      'ofLlSpecialiteArabe': instance.ofLlSpecialiteArabe,
      'ofLlSpecialite': instance.ofLlSpecialite,
      'individuId': instance.individuId,
      'nin': instance.nin,
      'individuNomArabe': instance.individuNomArabe,
      'individuNomLatin': instance.individuNomLatin,
      'individuPrenomArabe': instance.individuPrenomArabe,
      'individuPrenomLatin': instance.individuPrenomLatin,
      'individuDateNaissance': instance.individuDateNaissance,
      'individuLieuNaissance': instance.individuLieuNaissance,
      'individuLieuNaissanceArabe': instance.individuLieuNaissanceArabe,
      'refEtablissementId': instance.refEtablissementId,
      'refCodeEtablissement': instance.refCodeEtablissement,
      'llEtablissementArabe': instance.llEtablissementArabe,
      'llEtablissementLatin': instance.llEtablissementLatin,
      'moyenneBac': instance.moyenneBac,
      'lastMoyenne': instance.lastMoyenne,
      'photo': instance.photo,
      'cycleId': instance.cycleId,
      'cycleCode': instance.cycleCode,
      'cycleLibelleLongLt': instance.cycleLibelleLongLt,
      'niveauId': instance.niveauId,
      'niveauCode': instance.niveauCode,
      'niveauRang': instance.niveauRang,
      'niveauLibelleLongLt': instance.niveauLibelleLongLt,
      'niveauLibelleLongAr': instance.niveauLibelleLongAr,
    };
